AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ApplicationName:
    Type: String
    Description: "[optional] name of the application (leave empty to create new application)"
  EnvironmentName:
    Type: String
    Description: "[optional] name of the environment (leave empty to generate name)"
  KeyName:
    # use String instead of AWS::EC2::KeyPair::KeyName to allow empty values
    Type: String
    Description: "[optional] name of key pair to use for SSH access"
  IamInstanceProfile:
    Type: String
    Default: "aws-elasticbeanstalk-ec2-role"
    Description: "https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/iam-instanceprofile.html"
  CertbotEmail:
    Type: String
    Description: "email address to use for certificate creation using certbot"

Conditions:
  ApplicationNameNotSpecified: !Equals [!Ref ApplicationName, ""]
  KeyNameSpecified: !Not [!Equals [!Ref KeyName, ""]]

Resources:
  ApplicationTemp:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticbeanstalk-application.html
    Type: AWS::ElasticBeanstalk::Application
    Condition: ApplicationNameNotSpecified
    Properties:
      Description: "Temporary application for testing single-instance HTTPS configuration"

  EnvironmentTemp:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticbeanstalk-environment.html
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !If [ApplicationNameNotSpecified, !Ref ApplicationTemp, !Ref ApplicationName]
      EnvironmentName: !Ref EnvironmentName
      Description: "Temporary environment for testing single-instance HTTPS configuration"
      TemplateName: !If [KeyNameSpecified, !Ref ConfigTemplateWithKey, !Ref ConfigTemplateWithoutKey]

  ConfigTemplateWithoutKey:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticbeanstalk-configurationtemplate.html
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !If [ApplicationNameNotSpecified, !Ref ApplicationTemp, !Ref ApplicationName]
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.python
      SolutionStackName: "64bit Amazon Linux 2023 v4.1.0 running Python 3.11"
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html
      OptionSettings:
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: "IamInstanceProfile"
          Value: !Ref IamInstanceProfile
        - Namespace: "aws:ec2:instances"
          OptionName: "InstanceTypes"
          Value: "t4g.micro"
        - Namespace: "aws:elasticbeanstalk:environment"
          OptionName: "EnvironmentType"
          Value: "SingleInstance"
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: "CERTBOT_EMAIL"
          Value: !Ref CertbotEmail

  ConfigTemplateWithKey:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Condition: KeyNameSpecified
    Properties:
      ApplicationName: !If [ApplicationNameNotSpecified, !Ref ApplicationTemp, !Ref ApplicationName]
      SourceConfiguration:
        ApplicationName: !If [ApplicationNameNotSpecified, !Ref ApplicationTemp, !Ref ApplicationName]
        TemplateName: !Ref ConfigTemplateWithoutKey
      OptionSettings:
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: "EC2KeyName"
          Value: !Ref KeyName
